# Setup
title:               Kapitalturbo
tagline:             'Ein Blog über das Investieren in einer GmbH'
description:         'Erfahrungen zum Gründen und Handeln von Wertpapieren in einer GmbH'
url:                 https://blog.kapitalturbo.com
paginate:            20
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
